apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencite

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: opencite
  app.kubernetes.io/managed-by: kustomize

# Uncomment to customize image
# images:
#   - name: opencite
#     newName: your-registry/opencite
#     newTag: v1.0.0
